export const REGULAR_LIMIT = 80;
export const CREATE_TREASURY_LIMIT = 150;
export const SIGNER_APPROVE_LIMIT = 250;
export const SIGNED_LIMIT = 300;
export const EXECUTE_ACTION_LIMIT = 350;
export const CURRENT_USER_SESSION_KEY = "CURRENT_USER";
