export const REGULAR_LIMIT = 60;
export const CREATE_TREASURY_LIMIT = 77;
export const SIGNER_APPROVE_LIMIT = 230;
export const SIGNED_LIMIT = 300;
export const EXECUTE_ACTION_LIMIT = 350;
export const CURRENT_USER_SESSION_KEY = "CURRENT_USER";
